### ISSUE TITLE
Not an issue, just a question

### ISSUE THREAD

**Issue by Valkatastz** [ekralc/holsters#2]
I was wondering where is the function you declare for the animation when taking out the pistol ? The one that the multiplayer ped's hand is reaching for the holster? I want to add a waiting of 700 ms to it... Coz at the moment is unrealistic quick.

**Comment by ekralc** [comment]
There's another version of this script that's been circulating for a while that has animations (terribly) implemented, so I assume that's what you're referring to. I've never put animations in this myself but I plan to in the future when I eventually rewrite this.

**Comment by Valkatastz** [comment]
Thanks mate :) appreciated.
